[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.portray]
modules = ["metadynminer"]

[tool.portray.mkdocs]
plugins = ["mkdocs-jupyter", "search"]

nav = [{ Home = "README.md" }, { Tutorial = "docs/example/tutorial.ipynb" }]